version: '3'
services:
  web-service:
    build: .
    ports:
      - "3000:3000"
    links:
      - api-service
    depends_on:
      - api-service
  api-service:
    build: ./api
    environment:
      PASSWORD: ""
    ports:
      - "5000"
